[package]
name = "rside"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
eventsource-client = "0.15.0"
futures = "0.3.31"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.141"
tokio = { version = "1.0", features = ["full"] }
turso = "0.1.3"
